//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowManagerAdministrationUtilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkflowManagerAdministrationUtilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Workspaces.
        /// </summary>
        internal static string CAT_DATA_WORKSPACE_UTILS {
            get {
                return ResourceManager.GetString("CAT_DATA_WORKSPACE_UTILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string CAT_JOB_UTILS {
            get {
                return ResourceManager.GetString("CAT_JOB_UTILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Documents.
        /// </summary>
        internal static string CAT_MXD_UTILS {
            get {
                return ResourceManager.GetString("CAT_MXD_UTILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string CAT_NOTIFICATION_UTILS {
            get {
                return ResourceManager.GetString("CAT_NOTIFICATION_UTILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string CAT_SECURITY_UTILS {
            get {
                return ResourceManager.GetString("CAT_SECURITY_UTILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Assistant Workbooks.
        /// </summary>
        internal static string CAT_TAM_UTILS {
            get {
                return ResourceManager.GetString("CAT_TAM_UTILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Manager Database.
        /// </summary>
        internal static string CAT_WMX_DB_UTILS {
            get {
                return ResourceManager.GetString("CAT_WMX_DB_UTILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string CONST_JOB_QUERY_SEP {
            get {
                return ResourceManager.GetString("CONST_JOB_QUERY_SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to be attached to the job.
        /// </summary>
        internal static string DESC_AA_ATTACHMENT {
            get {
                return ResourceManager.GetString("DESC_AA_ATTACHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the file should be attached to the job.
        /// </summary>
        internal static string DESC_AA_ATTACHMENT_TYPE {
            get {
                return ResourceManager.GetString("DESC_AA_ATTACHMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the job to which the attachment will be added.
        /// </summary>
        internal static string DESC_AA_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_AA_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the job to which the attachment was added (output).
        /// </summary>
        internal static string DESC_AA_OUT_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_AA_OUT_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of Interest (polygon layer with exactly one selected feature).
        /// </summary>
        internal static string DESC_AAE_ALTERNATE_AOI {
            get {
                return ResourceManager.GetString("DESC_AAE_ALTERNATE_AOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric operation (ex: notifier AOI &lt;xxx&gt; feature).
        /// </summary>
        internal static string DESC_AAE_GEOMETRIC_OPERATION {
            get {
                return ResourceManager.GetString("DESC_AAE_GEOMETRIC_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Spatial Notification.
        /// </summary>
        internal static string DESC_AAE_SPATIAL_NOTIFICATION {
            get {
                return ResourceManager.GetString("DESC_AAE_SPATIAL_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Spatial Notification (output).
        /// </summary>
        internal static string DESC_AAE_SPATIAL_NOTIFICATION_OUT {
            get {
                return ResourceManager.GetString("DESC_AAE_SPATIAL_NOTIFICATION_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the inverse of the geometric operation above (ex: notifier AOI does not &lt;xxx&gt; feature).
        /// </summary>
        internal static string DESC_AAE_USE_INVERSE {
            get {
                return ResourceManager.GetString("DESC_AAE_USE_INVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the AOI of the job being worked as the notifier AOI.
        /// </summary>
        internal static string DESC_AAE_USE_JOB_AOI {
            get {
                return ResourceManager.GetString("DESC_AAE_USE_JOB_AOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment to be added to the job.
        /// </summary>
        internal static string DESC_ACTJ_COMMENT {
            get {
                return ResourceManager.GetString("DESC_ACTJ_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the job to which the comment will be added.
        /// </summary>
        internal static string DESC_ACTJ_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_ACTJ_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the job to which the comment was added (output).
        /// </summary>
        internal static string DESC_ACTJ_OUT_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_ACTJ_OUT_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change condition (how/when to check the where clauses).
        /// </summary>
        internal static string DESC_ADC_CHANGE_CONDITION {
            get {
                return ResourceManager.GetString("DESC_ADC_CHANGE_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns to monitor.
        /// </summary>
        internal static string DESC_ADC_COLUMNS {
            get {
                return ResourceManager.GetString("DESC_ADC_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Manager Data Workspace.
        /// </summary>
        internal static string DESC_ADC_DATA_WORKSPACE {
            get {
                return ResourceManager.GetString("DESC_ADC_DATA_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature class to monitor.
        /// </summary>
        internal static string DESC_ADC_FEATURE_CLASS {
            get {
                return ResourceManager.GetString("DESC_ADC_FEATURE_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor all columns for changes.
        /// </summary>
        internal static string DESC_ADC_MONITOR_ALL_COLUMNS {
            get {
                return ResourceManager.GetString("DESC_ADC_MONITOR_ALL_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Spatial Notification.
        /// </summary>
        internal static string DESC_ADC_SPATIAL_NOTIFICATION {
            get {
                return ResourceManager.GetString("DESC_ADC_SPATIAL_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Spatial Notification (output).
        /// </summary>
        internal static string DESC_ADC_SPATIAL_NOTIFICATION_OUT {
            get {
                return ResourceManager.GetString("DESC_ADC_SPATIAL_NOTIFICATION_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use/add to an existing dataset evaluator, if one is available.
        /// </summary>
        internal static string DESC_ADC_TRY_EXISTING_EVALUATOR {
            get {
                return ResourceManager.GetString("DESC_ADC_TRY_EXISTING_EVALUATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute (from the selected feature class).
        /// </summary>
        internal static string DESC_ADC_VT_ATTRIBUTE {
            get {
                return ResourceManager.GetString("DESC_ADC_VT_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator ( &lt;, &lt;=, &gt;, &gt;=, =, &lt;&gt;, or Contains ).
        /// </summary>
        internal static string DESC_ADC_VT_OPERATOR {
            get {
                return ResourceManager.GetString("DESC_ADC_VT_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string DESC_ADC_VT_VALUE {
            get {
                return ResourceManager.GetString("DESC_ADC_VT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions to monitor (a.k.a. where clauses).
        /// </summary>
        internal static string DESC_ADC_WHERE_CLAUSES {
            get {
                return ResourceManager.GetString("DESC_ADC_WHERE_CLAUSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or group name of assignee.
        /// </summary>
        internal static string DESC_AJ_ASSIGNEE {
            get {
                return ResourceManager.GetString("DESC_AJ_ASSIGNEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of assignment to make.
        /// </summary>
        internal static string DESC_AJ_ASSIGNEE_TYPE {
            get {
                return ResourceManager.GetString("DESC_AJ_ASSIGNEE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of job to assign.
        /// </summary>
        internal static string DESC_AJ_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_AJ_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of job assigned (output).
        /// </summary>
        internal static string DESC_AJ_OUT_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_AJ_OUT_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target .jxl file.
        /// </summary>
        internal static string DESC_BW_JXL_FILE_PATH {
            get {
                return ResourceManager.GetString("DESC_BW_JXL_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty-print output file.
        /// </summary>
        internal static string DESC_BW_PRETTY_PRINT {
            get {
                return ResourceManager.GetString("DESC_BW_PRETTY_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior on error.
        /// </summary>
        internal static string DESC_CDW_ERROR_BEHAVIOR {
            get {
                return ResourceManager.GetString("DESC_CDW_ERROR_BEHAVIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Workbook (Microsoft Excel).
        /// </summary>
        internal static string DESC_CDW_EXCEL_FILE_PATH {
            get {
                return ResourceManager.GetString("DESC_CDW_EXCEL_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspaces created (output).
        /// </summary>
        internal static string DESC_CDW_WORKSPACES_CREATED {
            get {
                return ResourceManager.GetString("DESC_CDW_WORKSPACES_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of interest (polygon layer with exactly one selected feature).
        /// </summary>
        internal static string DESC_CJ_AOI {
            get {
                return ResourceManager.GetString("DESC_CJ_AOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of assignee.
        /// </summary>
        internal static string DESC_CJ_ASSIGNEE {
            get {
                return ResourceManager.GetString("DESC_CJ_ASSIGNEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of assignee.
        /// </summary>
        internal static string DESC_CJ_ASSIGNEE_TYPE {
            get {
                return ResourceManager.GetString("DESC_CJ_ASSIGNEE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Manager data workspace.
        /// </summary>
        internal static string DESC_CJ_DATA_WORKSPACE {
            get {
                return ResourceManager.GetString("DESC_CJ_DATA_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date (mm/dd/yyyy).
        /// </summary>
        internal static string DESC_CJ_DUE_DATE {
            get {
                return ResourceManager.GetString("DESC_CJ_DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute new job after creation.
        /// </summary>
        internal static string DESC_CJ_EXECUTE_NEW_JOB {
            get {
                return ResourceManager.GetString("DESC_CJ_EXECUTE_NEW_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job owner (username).
        /// </summary>
        internal static string DESC_CJ_JOB_OWNER {
            get {
                return ResourceManager.GetString("DESC_CJ_JOB_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of job to create.
        /// </summary>
        internal static string DESC_CJ_JOB_TYPE {
            get {
                return ResourceManager.GetString("DESC_CJ_JOB_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of newly-created job.
        /// </summary>
        internal static string DESC_CJ_OUTPUT_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_CJ_OUTPUT_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent job ID.
        /// </summary>
        internal static string DESC_CJ_PARENT_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_CJ_PARENT_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent version.
        /// </summary>
        internal static string DESC_CJ_PARENT_VERSION {
            get {
                return ResourceManager.GetString("DESC_CJ_PARENT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string DESC_CJ_PRIORITY {
            get {
                return ResourceManager.GetString("DESC_CJ_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date (mm/dd/yyyy).
        /// </summary>
        internal static string DESC_CJ_START_DATE {
            get {
                return ResourceManager.GetString("DESC_CJ_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of job that was closed (output).
        /// </summary>
        internal static string DESC_CLJ_JOB_CLOSED {
            get {
                return ResourceManager.GetString("DESC_CLJ_JOB_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of job to close.
        /// </summary>
        internal static string DESC_CLJ_JOB_TO_CLOSE {
            get {
                return ResourceManager.GetString("DESC_CLJ_JOB_TO_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Manager database alias.
        /// </summary>
        internal static string DESC_COM_WMX_DATABASE {
            get {
                return ResourceManager.GetString("DESC_COM_WMX_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of new spatial notification.
        /// </summary>
        internal static string DESC_CSN_DESCRIPTION {
            get {
                return ResourceManager.GetString("DESC_CSN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail notification type to use as a template for the spatial notification&apos;s e-mail.
        /// </summary>
        internal static string DESC_CSN_EMAIL_NOTIFIER {
            get {
                return ResourceManager.GetString("DESC_CSN_EMAIL_NOTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new spatial notification.
        /// </summary>
        internal static string DESC_CSN_NAME {
            get {
                return ResourceManager.GetString("DESC_CSN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new spatial notification (output).
        /// </summary>
        internal static string DESC_CSN_OUT_NAME {
            get {
                return ResourceManager.GetString("DESC_CSN_OUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize multiple changes in a single notification message.
        /// </summary>
        internal static string DESC_CSN_SUMMARIZE {
            get {
                return ResourceManager.GetString("DESC_CSN_SUMMARIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of new spatial notification.
        /// </summary>
        internal static string DESC_CSN2_DESCRIPTION {
            get {
                return ResourceManager.GetString("DESC_CSN2_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body of the e-mail message.
        /// </summary>
        internal static string DESC_CSN2_MESSAGE {
            get {
                return ResourceManager.GetString("DESC_CSN2_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new spatial notification.
        /// </summary>
        internal static string DESC_CSN2_NAME {
            get {
                return ResourceManager.GetString("DESC_CSN2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of new spatial notification (output).
        /// </summary>
        internal static string DESC_CSN2_OUT_NAME {
            get {
                return ResourceManager.GetString("DESC_CSN2_OUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address to be used for the sender (default uses Workflow Manager system notification settings).
        /// </summary>
        internal static string DESC_CSN2_SENDER_EMAIL {
            get {
                return ResourceManager.GetString("DESC_CSN2_SENDER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name to be used for the sender (default uses Workflow Manager system notification settings).
        /// </summary>
        internal static string DESC_CSN2_SENDER_NAME {
            get {
                return ResourceManager.GetString("DESC_CSN2_SENDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject line for the e-mail notification.
        /// </summary>
        internal static string DESC_CSN2_SUBJECT {
            get {
                return ResourceManager.GetString("DESC_CSN2_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient list for the notification (tokens are allowed; use semicolons to delimit names).
        /// </summary>
        internal static string DESC_CSN2_SUBSCRIBERS {
            get {
                return ResourceManager.GetString("DESC_CSN2_SUBSCRIBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize multiple changes in a single notification message.
        /// </summary>
        internal static string DESC_CSN2_SUMMARIZE {
            get {
                return ResourceManager.GetString("DESC_CSN2_SUMMARIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of data workspace to be deleted.
        /// </summary>
        internal static string DESC_DDW_DATA_WORKSPACE {
            get {
                return ResourceManager.GetString("DESC_DDW_DATA_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of deleted workspace.
        /// </summary>
        internal static string DESC_DDW_OUT_DATA_WORKSPACE {
            get {
                return ResourceManager.GetString("DESC_DDW_OUT_DATA_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map document to be deleted from the Workflow Manager database.
        /// </summary>
        internal static string DESC_DELMXD_MAP_DOCUMENT {
            get {
                return ResourceManager.GetString("DESC_DELMXD_MAP_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map document that was deleted.
        /// </summary>
        internal static string DESC_DELMXD_OUT_MAP_DOCUMENT {
            get {
                return ResourceManager.GetString("DESC_DELMXD_OUT_MAP_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Task Assistant workbook that was deleted.
        /// </summary>
        internal static string DESC_DELTAM_OUT_WORKBOOK {
            get {
                return ResourceManager.GetString("DESC_DELTAM_OUT_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Assistant workbook to be deleted from the Workflow Manager database.
        /// </summary>
        internal static string DESC_DELTAM_WORKBOOK {
            get {
                return ResourceManager.GetString("DESC_DELTAM_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of job that was deleted (output).
        /// </summary>
        internal static string DESC_DJ_JOB_DELETED {
            get {
                return ResourceManager.GetString("DESC_DJ_JOB_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of job to delete.
        /// </summary>
        internal static string DESC_DJ_JOB_TO_DELETE {
            get {
                return ResourceManager.GetString("DESC_DJ_JOB_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Map Document (path to output MXD file).
        /// </summary>
        internal static string DESC_DMXD_MXD_FILE_PATH {
            get {
                return ResourceManager.GetString("DESC_DMXD_MXD_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name (name of MXD to retrieve from database).
        /// </summary>
        internal static string DESC_DMXD_SOURCE_NAME {
            get {
                return ResourceManager.GetString("DESC_DMXD_SOURCE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of orphaned types for which to check.
        /// </summary>
        internal static string DESC_DOT_CHECKLIST {
            get {
                return ResourceManager.GetString("DESC_DOT_CHECKLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of items deleted (output).
        /// </summary>
        internal static string DESC_DOT_NUM_ITEMS_DELETED {
            get {
                return ResourceManager.GetString("DESC_DOT_NUM_ITEMS_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview changes (do not actually delete any items).
        /// </summary>
        internal static string DESC_DOT_PREVIEW_CHANGES {
            get {
                return ResourceManager.GetString("DESC_DOT_PREVIEW_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name (name of TA workbook to retrieve from database).
        /// </summary>
        internal static string DESC_DTAM_SOURCE_NAME {
            get {
                return ResourceManager.GetString("DESC_DTAM_SOURCE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Workbook (path to output Task Assistant workbook XML file).
        /// </summary>
        internal static string DESC_DTAM_XML_FILE_PATH {
            get {
                return ResourceManager.GetString("DESC_DTAM_XML_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target workbook (Microsoft Excel).
        /// </summary>
        internal static string DESC_EDW_EXCEL_FILE_PATH {
            get {
                return ResourceManager.GetString("DESC_EDW_EXCEL_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of job to execute.
        /// </summary>
        internal static string DESC_EJ_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_EJ_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of executed job (output).
        /// </summary>
        internal static string DESC_EJ_OUT_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_EJ_OUT_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD group containing the full list of Workflow Manager groups (which themselves contain user assignments).
        /// </summary>
        internal static string DESC_IADC_GROUP_GROUP {
            get {
                return ResourceManager.GetString("DESC_IADC_GROUP_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of groups imported (output).
        /// </summary>
        internal static string DESC_IADC_OUT_NUM_GROUPS {
            get {
                return ResourceManager.GetString("DESC_IADC_OUT_NUM_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of users imported (output).
        /// </summary>
        internal static string DESC_IADC_OUT_NUM_USERS {
            get {
                return ResourceManager.GetString("DESC_IADC_OUT_NUM_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve the executing user&apos;s login in the database (even if it&apos;s removed from the AD).
        /// </summary>
        internal static string DESC_IADC_PRESERVE_CURRENT_USER {
            get {
                return ResourceManager.GetString("DESC_IADC_PRESERVE_CURRENT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD group containing the full list of Workflow Manager users.
        /// </summary>
        internal static string DESC_IADC_USER_GROUP {
            get {
                return ResourceManager.GetString("DESC_IADC_USER_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job ID List.
        /// </summary>
        internal static string DESC_LJ_JOB_ID_LIST {
            get {
                return ResourceManager.GetString("DESC_LJ_JOB_ID_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to {0} table (must match the default WMX DB location).
        /// </summary>
        internal static string DESC_LJ_JOBS_TABLE_1 {
            get {
                return ResourceManager.GetString("DESC_LJ_JOBS_TABLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL query (runs against the {0} table).
        /// </summary>
        internal static string DESC_LJ_SQL_QUERY_FILTER_1 {
            get {
                return ResourceManager.GetString("DESC_LJ_SQL_QUERY_FILTER_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of job IDs retrieved by this query.
        /// </summary>
        internal static string DESC_LJUQ_OUT_JOB_IDS {
            get {
                return ResourceManager.GetString("DESC_LJUQ_OUT_JOB_IDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the query to use.
        /// </summary>
        internal static string DESC_LJUQ_QUERY_NAME {
            get {
                return ResourceManager.GetString("DESC_LJUQ_QUERY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Document List.
        /// </summary>
        internal static string DESC_LMXD_MAP_DOCUMENT_LIST {
            get {
                return ResourceManager.GetString("DESC_LMXD_MAP_DOCUMENT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Assistant Workbook List.
        /// </summary>
        internal static string DESC_LTAM_TAM_WORKBOOK_LIST {
            get {
                return ResourceManager.GetString("DESC_LTAM_TAM_WORKBOOK_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of group to list (blank lists all users).
        /// </summary>
        internal static string DESC_LU_GROUP_NAME {
            get {
                return ResourceManager.GetString("DESC_LU_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users (output).
        /// </summary>
        internal static string DESC_LU_USER_NAME_LIST {
            get {
                return ResourceManager.GetString("DESC_LU_USER_NAME_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all data workspaces.
        /// </summary>
        internal static string DESC_LWSP_DATA_WORKSPACE_LIST {
            get {
                return ResourceManager.GetString("DESC_LWSP_DATA_WORKSPACE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name (out).
        /// </summary>
        internal static string DESC_MAA_OUT_USER_NAME {
            get {
                return ResourceManager.GetString("DESC_MAA_OUT_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve the executing user&apos;s administrative access to the DB.
        /// </summary>
        internal static string DESC_MAA_PRESERVE_CURRENT_USER {
            get {
                return ResourceManager.GetString("DESC_MAA_PRESERVE_CURRENT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether to grant or revoke adminstrator access for the given user(s).
        /// </summary>
        internal static string DESC_MAA_PRIVILEGE_ACTION {
            get {
                return ResourceManager.GetString("DESC_MAA_PRIVILEGE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name (&quot;[All]&quot; selects all users).
        /// </summary>
        internal static string DESC_MAA_USER_NAME {
            get {
                return ResourceManager.GetString("DESC_MAA_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name (&quot;[All]&quot; selects all groups).
        /// </summary>
        internal static string DESC_MPA_GROUP_NAME {
            get {
                return ResourceManager.GetString("DESC_MPA_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege name (out).
        /// </summary>
        internal static string DESC_MPA_OUT_PRIVILEGE_NAME {
            get {
                return ResourceManager.GetString("DESC_MPA_OUT_PRIVILEGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether to grant or revoke the specified privilege(s) for the given group(s).
        /// </summary>
        internal static string DESC_MPA_PRIVILEGE_ACTION {
            get {
                return ResourceManager.GetString("DESC_MPA_PRIVILEGE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege name (&quot;[All]&quot; selects all privileges).
        /// </summary>
        internal static string DESC_MPA_PRIVILEGE_NAME {
            get {
                return ResourceManager.GetString("DESC_MPA_PRIVILEGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of potential problems for which to check.
        /// </summary>
        internal static string DESC_RPE_CHECKLIST {
            get {
                return ResourceManager.GetString("DESC_RPE_CHECKLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of a text file to which problem descriptions will be written.
        /// </summary>
        internal static string DESC_RPE_OUT_LOG_FILE_PATH {
            get {
                return ResourceManager.GetString("DESC_RPE_OUT_LOG_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of potential problems found by the tool.
        /// </summary>
        internal static string DESC_RPE_OUT_NUM_ISSUES_FOUND {
            get {
                return ResourceManager.GetString("DESC_RPE_OUT_NUM_ISSUES_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default data workspace for this job type.
        /// </summary>
        internal static string DESC_SDW_DATA_WORKSPACE {
            get {
                return ResourceManager.GetString("DESC_SDW_DATA_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job type name.
        /// </summary>
        internal static string DESC_SDW_JOB_TYPE {
            get {
                return ResourceManager.GetString("DESC_SDW_JOB_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default data workspace (output).
        /// </summary>
        internal static string DESC_SDW_OUT_DATA_WORKSPACE {
            get {
                return ResourceManager.GetString("DESC_SDW_OUT_DATA_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default parent version for this job type.
        /// </summary>
        internal static string DESC_SDW_PARENT_VERSION {
            get {
                return ResourceManager.GetString("DESC_SDW_PARENT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of job for which the notification will be sent.
        /// </summary>
        internal static string DESC_SJN_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_SJN_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of notification to send.
        /// </summary>
        internal static string DESC_SJN_NOTIFICATION_NAME {
            get {
                return ResourceManager.GetString("DESC_SJN_NOTIFICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of job for which the notification was sent.
        /// </summary>
        internal static string DESC_SJN_OUT_JOB_ID {
            get {
                return ResourceManager.GetString("DESC_SJN_OUT_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the map document (default/unchanged if blank).
        /// </summary>
        internal static string DESC_UMXD_DESCRIPTION {
            get {
                return ResourceManager.GetString("DESC_UMXD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source map document (path to MXD file).
        /// </summary>
        internal static string DESC_UMXD_MXD_FILE_PATH {
            get {
                return ResourceManager.GetString("DESC_UMXD_MXD_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the map document in the Workflow Manager database after upload (output).
        /// </summary>
        internal static string DESC_UMXD_OUT_TARGET_NAME {
            get {
                return ResourceManager.GetString("DESC_UMXD_OUT_TARGET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing map documents of the same name.
        /// </summary>
        internal static string DESC_UMXD_OVERWRITE_EXISTING {
            get {
                return ResourceManager.GetString("DESC_UMXD_OVERWRITE_EXISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category in which to store the map document (default/unchanged if blank).
        /// </summary>
        internal static string DESC_UMXD_TARGET_CATEGORY {
            get {
                return ResourceManager.GetString("DESC_UMXD_TARGET_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the map document in the Workflow Manager database after upload.
        /// </summary>
        internal static string DESC_UMXD_TARGET_NAME {
            get {
                return ResourceManager.GetString("DESC_UMXD_TARGET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the TAM workbook in the Workflow Manager database after upload (output).
        /// </summary>
        internal static string DESC_UTAM_OUT_TARGET_NAME {
            get {
                return ResourceManager.GetString("DESC_UTAM_OUT_TARGET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing workbooks of the same name.
        /// </summary>
        internal static string DESC_UTAM_OVERWRITE_EXISTING {
            get {
                return ResourceManager.GetString("DESC_UTAM_OVERWRITE_EXISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the TAM workbook in Workflow Manager database after upload.
        /// </summary>
        internal static string DESC_UTAM_TARGET_NAME {
            get {
                return ResourceManager.GetString("DESC_UTAM_TARGET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source workbook (path to Task Assistant workbook XML file).
        /// </summary>
        internal static string DESC_UTAM_XML_FILE_PATH {
            get {
                return ResourceManager.GetString("DESC_UTAM_XML_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem adding an area evaluator to the specified spatial notifier.
        /// </summary>
        internal static string ERROR_ADD_AREA_EVALUATOR {
            get {
                return ResourceManager.GetString("ERROR_ADD_AREA_EVALUATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem adding a dataset condition to the specified spatial notifier/dataset evaluator.
        /// </summary>
        internal static string ERROR_ADD_DATASET_CONDITION {
            get {
                return ResourceManager.GetString("ERROR_ADD_DATASET_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General problem wirh AOI layer; ensure that it is an in-memory layer (not a feature class), that any DB connection is valid, etc..
        /// </summary>
        internal static string ERROR_AOI_INPUT {
            get {
                return ResourceManager.GetString("ERROR_AOI_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only polygon features may be used for AOI definition.
        /// </summary>
        internal static string ERROR_AOI_NOT_POLYGON {
            get {
                return ResourceManager.GetString("ERROR_AOI_NOT_POLYGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed job AOI overlaps with one or more existing jobs (not allowed by system policy).
        /// </summary>
        internal static string ERROR_AOI_OVERLAP {
            get {
                return ResourceManager.GetString("ERROR_AOI_OVERLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified job cannot be closed at this time.
        /// </summary>
        internal static string ERROR_CANNOT_CLOSE_JOB {
            get {
                return ResourceManager.GetString("ERROR_CANNOT_CLOSE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem creating the job.
        /// </summary>
        internal static string ERROR_CREATE_JOB {
            get {
                return ResourceManager.GetString("ERROR_CREATE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem deleting the job.
        /// </summary>
        internal static string ERROR_DELETE_JOB {
            get {
                return ResourceManager.GetString("ERROR_DELETE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem deleting the job&apos;s version.
        /// </summary>
        internal static string ERROR_DELETE_JOB_VERSION {
            get {
                return ResourceManager.GetString("ERROR_DELETE_JOB_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem deleting the specified map document from the Workflow Manager database.
        /// </summary>
        internal static string ERROR_DELETE_MXD {
            get {
                return ResourceManager.GetString("ERROR_DELETE_MXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem deleting the specified Task Assistant workbook from the Workflow Manager database.
        /// </summary>
        internal static string ERROR_DELETE_TAM {
            get {
                return ResourceManager.GetString("ERROR_DELETE_TAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date cannot be earlier than the start date.
        /// </summary>
        internal static string ERROR_DUE_DATE_LT_START_DATE {
            get {
                return ResourceManager.GetString("ERROR_DUE_DATE_LT_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem opening the Excel workbook.
        /// </summary>
        internal static string ERROR_EXCEL_WORKBOOK {
            get {
                return ResourceManager.GetString("ERROR_EXCEL_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing the Excel worksheet.
        /// </summary>
        internal static string ERROR_EXCEL_WORKSHEET {
            get {
                return ResourceManager.GetString("ERROR_EXCEL_WORKSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of selected features; exactly one feature must be selected in AOI layer if a layer is specified.
        /// </summary>
        internal static string ERROR_EXPECTED_ONE_SELECTED_FEATURE {
            get {
                return ResourceManager.GetString("ERROR_EXPECTED_ONE_SELECTED_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem accessing file.
        /// </summary>
        internal static string ERROR_FILE_ACCESS {
            get {
                return ResourceManager.GetString("ERROR_FILE_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Workflow Manager database is invalid or inaccessible.
        /// </summary>
        internal static string ERROR_INVALID_WMX_DB {
            get {
                return ResourceManager.GetString("ERROR_INVALID_WMX_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee type is not specified; assignee will be ignored.
        /// </summary>
        internal static string ERROR_JOB_ASSIGNMENT_IGNORED {
            get {
                return ResourceManager.GetString("ERROR_JOB_ASSIGNMENT_IGNORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing job.
        /// </summary>
        internal static string ERROR_JOB_EXECUTION {
            get {
                return ResourceManager.GetString("ERROR_JOB_EXECUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get an int value from the retrieved job ID; is a Workflow Manager table corrupt?.
        /// </summary>
        internal static string ERROR_JOB_ID_PARSE {
            get {
                return ResourceManager.GetString("ERROR_JOB_ID_PARSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem saving the .jxl file.
        /// </summary>
        internal static string ERROR_JXL_BACKUP {
            get {
                return ResourceManager.GetString("ERROR_JXL_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License problem; verify that core and Workflow Manager licenses are available and checked out, license server is reachable, etc..
        /// </summary>
        internal static string ERROR_LICENSE_RELATED {
            get {
                return ResourceManager.GetString("ERROR_LICENSE_RELATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem downloading the map document from the Workflow Manager database or saving it to file.
        /// </summary>
        internal static string ERROR_MXD_DOWNLOAD {
            get {
                return ResourceManager.GetString("ERROR_MXD_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem opening the map document or storing it to the Workflow Manager database.
        /// </summary>
        internal static string ERROR_MXD_UPLOAD {
            get {
                return ResourceManager.GetString("ERROR_MXD_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user does not have permission to add attachments to held jobs.
        /// </summary>
        internal static string ERROR_NO_ADD_ATTACHMENTS_HELD_JOBS {
            get {
                return ResourceManager.GetString("ERROR_NO_ADD_ATTACHMENTS_HELD_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user does not have permission to add comments to held jobs.
        /// </summary>
        internal static string ERROR_NO_ADD_COMMENTS_HELD_JOBS {
            get {
                return ResourceManager.GetString("ERROR_NO_ADD_COMMENTS_HELD_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user does not have permission to assign jobs.
        /// </summary>
        internal static string ERROR_NO_ASSIGN_JOB_PRIVILEGE {
            get {
                return ResourceManager.GetString("ERROR_NO_ASSIGN_JOB_PRIVILEGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user does not have permission to close jobs.
        /// </summary>
        internal static string ERROR_NO_CLOSE_JOB_PRIVILEGE {
            get {
                return ResourceManager.GetString("ERROR_NO_CLOSE_JOB_PRIVILEGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user does not have permission to create jobs.
        /// </summary>
        internal static string ERROR_NO_CREATE_JOB_PRIVILEGE {
            get {
                return ResourceManager.GetString("ERROR_NO_CREATE_JOB_PRIVILEGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user does not have permission to delete jobs.
        /// </summary>
        internal static string ERROR_NO_DELETE_JOB_PRIVILEGE {
            get {
                return ResourceManager.GetString("ERROR_NO_DELETE_JOB_PRIVILEGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user does not have permission to add/remove job attachments.
        /// </summary>
        internal static string ERROR_NO_MANAGE_ATTACHMENTS_PRIVILEGE {
            get {
                return ResourceManager.GetString("ERROR_NO_MANAGE_ATTACHMENTS_PRIVILEGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified job must have exactly one active/current step; multiple active steps (or no active steps) are not allowed.
        /// </summary>
        internal static string ERROR_NO_OR_MULTIPLE_STEPS {
            get {
                return ResourceManager.GetString("ERROR_NO_OR_MULTIPLE_STEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spatial notifications found in Workflow Manager database.
        /// </summary>
        internal static string ERROR_NO_SPATIAL_NOTIFICATIONS_FOUND {
            get {
                return ResourceManager.GetString("ERROR_NO_SPATIAL_NOTIFICATIONS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data workspaces found in Workflow Manager database.
        /// </summary>
        internal static string ERROR_NO_WORKSPACES_DEFINED {
            get {
                return ResourceManager.GetString("ERROR_NO_WORKSPACES_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator is not supported in this context; use one of &apos;&lt;&apos;, &apos;&lt;=&apos;, &apos;&gt;&apos;, &apos;&gt;=&apos;, &apos;=&apos;, &apos;&lt;&gt;&apos; or &apos;Contains&apos;.
        /// </summary>
        internal static string ERROR_OPERATOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_OPERATOR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the spatial notification.
        /// </summary>
        internal static string ERROR_SPATIAL_NOTIFICATION_CREATION {
            get {
                return ResourceManager.GetString("ERROR_SPATIAL_NOTIFICATION_CREATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A spatial notification with the given name already exists.
        /// </summary>
        internal static string ERROR_SPATIAL_NOTIFICATION_EXISTS {
            get {
                return ResourceManager.GetString("ERROR_SPATIAL_NOTIFICATION_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem downloading the Task Assistant workbook from the Workflow Manager database or saving it to file.
        /// </summary>
        internal static string ERROR_TAM_DOWNLOAD {
            get {
                return ResourceManager.GetString("ERROR_TAM_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem opening the Task Assistant workbook or storing it to the Workflow Manager database.
        /// </summary>
        internal static string ERROR_TAM_UPLOAD {
            get {
                return ResourceManager.GetString("ERROR_TAM_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified query cannot be found.
        /// </summary>
        internal static string ERROR_UNKNOWN_QUERY {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWN_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while running the tool.
        /// </summary>
        internal static string ERROR_UNSPECIFIED {
            get {
                return ResourceManager.GetString("ERROR_UNSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user is not an administrator on the Workflow Manager database.
        /// </summary>
        internal static string ERROR_USER_NOT_ADMIN {
            get {
                return ResourceManager.GetString("ERROR_USER_NOT_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified user not found in Workflow Manager database.
        /// </summary>
        internal static string ERROR_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the available versions for the specified data workspace.
        /// </summary>
        internal static string ERROR_VERSION_LOOKUP {
            get {
                return ResourceManager.GetString("ERROR_VERSION_LOOKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem connecting to workspace, or no versions detected?.
        /// </summary>
        internal static string ERROR_WORKSPACE {
            get {
                return ResourceManager.GetString("ERROR_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load a data workspace from the current spreadsheet row.
        /// </summary>
        internal static string ERROR_WORKSPACE_FETCH {
            get {
                return ResourceManager.GetString("ERROR_WORKSPACE_FETCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified data workspace cannot be found in the Workflow Manager database.
        /// </summary>
        internal static string ERROR_WORKSPACE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_WORKSPACE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string MSG_DONE {
            get {
                return ResourceManager.GetString("MSG_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Area Evaluator to Spatial Notification.
        /// </summary>
        internal static string TOOL_ADD_AREA_EVALUATOR_TO_SN {
            get {
                return ResourceManager.GetString("TOOL_ADD_AREA_EVALUATOR_TO_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachment to Job.
        /// </summary>
        internal static string TOOL_ADD_ATTACHMENT_TO_JOB {
            get {
                return ResourceManager.GetString("TOOL_ADD_ATTACHMENT_TO_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment to Job.
        /// </summary>
        internal static string TOOL_ADD_COMMENT_TO_JOB {
            get {
                return ResourceManager.GetString("TOOL_ADD_COMMENT_TO_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Dataset Condition to Spatial Notification.
        /// </summary>
        internal static string TOOL_ADD_DATASET_CONDITION_TO_SN {
            get {
                return ResourceManager.GetString("TOOL_ADD_DATASET_CONDITION_TO_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Job.
        /// </summary>
        internal static string TOOL_ASSIGN_JOB {
            get {
                return ResourceManager.GetString("TOOL_ASSIGN_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Workflow Manager Database.
        /// </summary>
        internal static string TOOL_BACKUP_WORKFLOW_MANAGER_DB {
            get {
                return ResourceManager.GetString("TOOL_BACKUP_WORKFLOW_MANAGER_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Job.
        /// </summary>
        internal static string TOOL_CLOSE_JOB {
            get {
                return ResourceManager.GetString("TOOL_CLOSE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Data Workspaces from Excel Spreadsheet.
        /// </summary>
        internal static string TOOL_CREATE_DATA_WORKSPACES_FROM_SPREADSHEET {
            get {
                return ResourceManager.GetString("TOOL_CREATE_DATA_WORKSPACES_FROM_SPREADSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job.
        /// </summary>
        internal static string TOOL_CREATE_JOB {
            get {
                return ResourceManager.GetString("TOOL_CREATE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Spatial Notification with E-mail Notifier.
        /// </summary>
        internal static string TOOL_CREATE_SPATIAL_NOTIFICATION_WITH_EMAIL {
            get {
                return ResourceManager.GetString("TOOL_CREATE_SPATIAL_NOTIFICATION_WITH_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Spatial Notification with E-mail Notifier 2.
        /// </summary>
        internal static string TOOL_CREATE_SPATIAL_NOTIFICATION_WITH_EMAIL_2 {
            get {
                return ResourceManager.GetString("TOOL_CREATE_SPATIAL_NOTIFICATION_WITH_EMAIL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Data Workspace.
        /// </summary>
        internal static string TOOL_DELETE_DATA_WORKSPACE {
            get {
                return ResourceManager.GetString("TOOL_DELETE_DATA_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Job.
        /// </summary>
        internal static string TOOL_DELETE_JOB {
            get {
                return ResourceManager.GetString("TOOL_DELETE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Map Document.
        /// </summary>
        internal static string TOOL_DELETE_MAP_DOCUMENT {
            get {
                return ResourceManager.GetString("TOOL_DELETE_MAP_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Orphaned Types.
        /// </summary>
        internal static string TOOL_DELETE_ORPHANED_TYPES {
            get {
                return ResourceManager.GetString("TOOL_DELETE_ORPHANED_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Task Assistant Workbook.
        /// </summary>
        internal static string TOOL_DELETE_TASK_ASSISTANT_WORKBOOK {
            get {
                return ResourceManager.GetString("TOOL_DELETE_TASK_ASSISTANT_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Map Document.
        /// </summary>
        internal static string TOOL_DOWNLOAD_MAP_DOCUMENT {
            get {
                return ResourceManager.GetString("TOOL_DOWNLOAD_MAP_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Task Assistant Workbook.
        /// </summary>
        internal static string TOOL_DOWNLOAD_TASK_ASSISTANT_WORKBOOK {
            get {
                return ResourceManager.GetString("TOOL_DOWNLOAD_TASK_ASSISTANT_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Job.
        /// </summary>
        internal static string TOOL_EXECUTE_JOB {
            get {
                return ResourceManager.GetString("TOOL_EXECUTE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data Workspaces to Excel Spreadsheet.
        /// </summary>
        internal static string TOOL_EXPORT_DATA_WORKSPACES_TO_SPREADSHEET {
            get {
                return ResourceManager.GetString("TOOL_EXPORT_DATA_WORKSPACES_TO_SPREADSHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Active Directory Configuration.
        /// </summary>
        internal static string TOOL_IMPORT_AD_CONFIG {
            get {
                return ResourceManager.GetString("TOOL_IMPORT_AD_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List All Data Workspaces.
        /// </summary>
        internal static string TOOL_LIST_ALL_DATA_WORKSPACES {
            get {
                return ResourceManager.GetString("TOOL_LIST_ALL_DATA_WORKSPACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List All Map Documents.
        /// </summary>
        internal static string TOOL_LIST_ALL_MAP_DOCUMENTS {
            get {
                return ResourceManager.GetString("TOOL_LIST_ALL_MAP_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List All Task Assistant Workbooks.
        /// </summary>
        internal static string TOOL_LIST_ALL_TASK_ASSISTANT_WORKBOOKS {
            get {
                return ResourceManager.GetString("TOOL_LIST_ALL_TASK_ASSISTANT_WORKBOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Jobs.
        /// </summary>
        internal static string TOOL_LIST_JOBS {
            get {
                return ResourceManager.GetString("TOOL_LIST_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Jobs Using Query.
        /// </summary>
        internal static string TOOL_LIST_JOBS_USING_QUERY {
            get {
                return ResourceManager.GetString("TOOL_LIST_JOBS_USING_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Users.
        /// </summary>
        internal static string TOOL_LIST_USERS {
            get {
                return ResourceManager.GetString("TOOL_LIST_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Administrator Access.
        /// </summary>
        internal static string TOOL_MODIFY_ADMIN_ACCESS {
            get {
                return ResourceManager.GetString("TOOL_MODIFY_ADMIN_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Privilege Assignment.
        /// </summary>
        internal static string TOOL_MODIFY_PRIVILEGE_ASSIGNMENT {
            get {
                return ResourceManager.GetString("TOOL_MODIFY_PRIVILEGE_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Possible Errors.
        /// </summary>
        internal static string TOOL_REPORT_POSSIBLE_ERRORS {
            get {
                return ResourceManager.GetString("TOOL_REPORT_POSSIBLE_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Job Notification.
        /// </summary>
        internal static string TOOL_SEND_JOB_NOTIFICATION {
            get {
                return ResourceManager.GetString("TOOL_SEND_JOB_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Workspace for Job Type.
        /// </summary>
        internal static string TOOL_SET_DEFAULT_WORKSPACE_FOR_JOB_TYPE {
            get {
                return ResourceManager.GetString("TOOL_SET_DEFAULT_WORKSPACE_FOR_JOB_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Map Document.
        /// </summary>
        internal static string TOOL_UPLOAD_MAP_DOCUMENT {
            get {
                return ResourceManager.GetString("TOOL_UPLOAD_MAP_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Task Assistant Workbook.
        /// </summary>
        internal static string TOOL_UPLOAD_TASK_ASSISTANT_WORKBOOK {
            get {
                return ResourceManager.GetString("TOOL_UPLOAD_TASK_ASSISTANT_WORKBOOK", resourceCulture);
            }
        }
    }
}
